
package com.travelport.service.universal_v50_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-06-13T20:09:03.759+06:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "PriceMatchError", targetNamespace = "http://www.travelport.com/schema/common_v50_0")
public class PriceFaultMessage extends Exception {
    
    private com.travelport.schema.common_v50_0.PriceMatchError priceMatchError;

    public PriceFaultMessage() {
        super();
    }
    
    public PriceFaultMessage(String message) {
        super(message);
    }
    
    public PriceFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public PriceFaultMessage(String message, com.travelport.schema.common_v50_0.PriceMatchError priceMatchError) {
        super(message);
        this.priceMatchError = priceMatchError;
    }

    public PriceFaultMessage(String message, com.travelport.schema.common_v50_0.PriceMatchError priceMatchError, Throwable cause) {
        super(message, cause);
        this.priceMatchError = priceMatchError;
    }

    public com.travelport.schema.common_v50_0.PriceMatchError getFaultInfo() {
        return this.priceMatchError;
    }
}
